//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SplitMergeTool.lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_us {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_us() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SplitMergeTool.lang.en-us", typeof(en_us).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please add the files needed for the merge first! 的本地化字符串。
        /// </summary>
        internal static string AddFileToMerge {
            get {
                return ResourceManager.GetString("AddFileToMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add new page merge 的本地化字符串。
        /// </summary>
        internal static string AddNewPageMerge {
            get {
                return ResourceManager.GetString("AddNewPageMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add text watermark 的本地化字符串。
        /// </summary>
        internal static string AddTextWatermark {
            get {
                return ResourceManager.GetString("AddTextWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All worksheets 的本地化字符串。
        /// </summary>
        internal static string AllWorksheets {
            get {
                return ResourceManager.GetString("AllWorksheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic information 的本地化字符串。
        /// </summary>
        internal static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese 的本地化字符串。
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose color 的本地化字符串。
        /// </summary>
        internal static string ChooseColor {
            get {
                return ResourceManager.GetString("ChooseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose font size 的本地化字符串。
        /// </summary>
        internal static string ChooseFontSize {
            get {
                return ResourceManager.GetString("ChooseFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a worksheet 的本地化字符串。
        /// </summary>
        internal static string ChooseWorksheet {
            get {
                return ResourceManager.GetString("ChooseWorksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This operation will delete the original file with the same name in the output file path, confirm the execution? 的本地化字符串。
        /// </summary>
        internal static string ConfirmExecution {
            get {
                return ResourceManager.GetString("ConfirmExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact 的本地化字符串。
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: Please indicate &quot;SplitMergeTool&quot; user when contacting 的本地化字符串。
        /// </summary>
        internal static string ContactNote {
            get {
                return ResourceManager.GetString("ContactNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conversion type does not match file format! 的本地化字符串。
        /// </summary>
        internal static string ConversionFormatNotMatch {
            get {
                return ResourceManager.GetString("ConversionFormatNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert 的本地化字符串。
        /// </summary>
        internal static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert Type 的本地化字符串。
        /// </summary>
        internal static string ConvertType {
            get {
                return ResourceManager.GetString("ConvertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The email address was copied successfully! 的本地化字符串。
        /// </summary>
        internal static string CopyEmailAddress {
            get {
                return ResourceManager.GetString("CopyEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mobile phone number copied successfully! 的本地化字符串。
        /// </summary>
        internal static string CopyPhoneNumber {
            get {
                return ResourceManager.GetString("CopyPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ number copied successfully! 的本地化字符串。
        /// </summary>
        internal static string CopyQQNumber {
            get {
                return ResourceManager.GetString("CopyQQNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CopyRight© 2019 Jay Chan. All Rights Reserved. 的本地化字符串。
        /// </summary>
        internal static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy to clipboard 的本地化字符串。
        /// </summary>
        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeChat number copied successfully! 的本地化字符串。
        /// </summary>
        internal static string CopyWeChatNumber {
            get {
                return ResourceManager.GetString("CopyWeChatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current time 的本地化字符串。
        /// </summary>
        internal static string CurrDate {
            get {
                return ResourceManager.GetString("CurrDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Designated worksheet 的本地化字符串。
        /// </summary>
        internal static string DesignatedWorksheet {
            get {
                return ResourceManager.GetString("DesignatedWorksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Document Manage 的本地化字符串。
        /// </summary>
        internal static string DocManage {
            get {
                return ResourceManager.GetString("DocManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Document Merge 的本地化字符串。
        /// </summary>
        internal static string DocMerge {
            get {
                return ResourceManager.GetString("DocMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Document Split 的本地化字符串。
        /// </summary>
        internal static string DocSplit {
            get {
                return ResourceManager.GetString("DocSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop Out 的本地化字符串。
        /// </summary>
        internal static string DropOut {
            get {
                return ResourceManager.GetString("DropOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter custom information! 的本地化字符串。
        /// </summary>
        internal static string EnterCustomContent {
            get {
                return ResourceManager.GetString("EnterCustomContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the number of files! 的本地化字符串。
        /// </summary>
        internal static string EnterFileCount {
            get {
                return ResourceManager.GetString("EnterFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a file name! 的本地化字符串。
        /// </summary>
        internal static string EnterFileName {
            get {
                return ResourceManager.GetString("EnterFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the file size! 的本地化字符串。
        /// </summary>
        internal static string EnterFileSize {
            get {
                return ResourceManager.GetString("EnterFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execution completed! 的本地化字符串。
        /// </summary>
        internal static string ExecutionCompleted {
            get {
                return ResourceManager.GetString("ExecutionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extended area 的本地化字符串。
        /// </summary>
        internal static string ExtendedArea {
            get {
                return ResourceManager.GetString("ExtendedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of files 的本地化字符串。
        /// </summary>
        internal static string FileCount {
            get {
                return ResourceManager.GetString("FileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Format Conversion Tool 的本地化字符串。
        /// </summary>
        internal static string FileFormatConversionTool {
            get {
                return ResourceManager.GetString("FileFormatConversionTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File length 的本地化字符串。
        /// </summary>
        internal static string FileLength {
            get {
                return ResourceManager.GetString("FileLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File list 的本地化字符串。
        /// </summary>
        internal static string FileList {
            get {
                return ResourceManager.GetString("FileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Split Merge Tool 的本地化字符串。
        /// </summary>
        internal static string FileManageTool {
            get {
                return ResourceManager.GetString("FileManageTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File name 的本地化字符串。
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File path 的本地化字符串。
        /// </summary>
        internal static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File path error! 的本地化字符串。
        /// </summary>
        internal static string FilePathError {
            get {
                return ResourceManager.GetString("FilePathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert files (for file drag and drop) 的本地化字符串。
        /// </summary>
        internal static string FilesConvert {
            get {
                return ResourceManager.GetString("FilesConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File size(Byte) 的本地化字符串。
        /// </summary>
        internal static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge files (for file drag and drop) 的本地化字符串。
        /// </summary>
        internal static string FilesMerged {
            get {
                return ResourceManager.GetString("FilesMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File type 的本地化字符串。
        /// </summary>
        internal static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Already the first item, can&apos;t move! 的本地化字符串。
        /// </summary>
        internal static string FirstItemCannotMove {
            get {
                return ResourceManager.GetString("FirstItemCannotMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font size 的本地化字符串。
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF to Word 的本地化字符串。
        /// </summary>
        internal static string FormatType0 {
            get {
                return ResourceManager.GetString("FormatType0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF to XPS 的本地化字符串。
        /// </summary>
        internal static string FormatType1 {
            get {
                return ResourceManager.GetString("FormatType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF to BMP 的本地化字符串。
        /// </summary>
        internal static string FormatType10 {
            get {
                return ResourceManager.GetString("FormatType10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF to GIF 的本地化字符串。
        /// </summary>
        internal static string FormatType11 {
            get {
                return ResourceManager.GetString("FormatType11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF to ICON 的本地化字符串。
        /// </summary>
        internal static string FormatType12 {
            get {
                return ResourceManager.GetString("FormatType12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF to Html 的本地化字符串。
        /// </summary>
        internal static string FormatType2 {
            get {
                return ResourceManager.GetString("FormatType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CSV to PDF 的本地化字符串。
        /// </summary>
        internal static string FormatType3 {
            get {
                return ResourceManager.GetString("FormatType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Word to PDF 的本地化字符串。
        /// </summary>
        internal static string FormatType4 {
            get {
                return ResourceManager.GetString("FormatType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XPS to PDF 的本地化字符串。
        /// </summary>
        internal static string FormatType5 {
            get {
                return ResourceManager.GetString("FormatType5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Html to PDF 的本地化字符串。
        /// </summary>
        internal static string FormatType6 {
            get {
                return ResourceManager.GetString("FormatType6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF to PNG 的本地化字符串。
        /// </summary>
        internal static string FormatType7 {
            get {
                return ResourceManager.GetString("FormatType7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel to PDF 的本地化字符串。
        /// </summary>
        internal static string FormatType8 {
            get {
                return ResourceManager.GetString("FormatType8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF to JPG 的本地化字符串。
        /// </summary>
        internal static string FormatType9 {
            get {
                return ResourceManager.GetString("FormatType9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Form Manage 的本地化字符串。
        /// </summary>
        internal static string FormManage {
            get {
                return ResourceManager.GetString("FormManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Form Merge 的本地化字符串。
        /// </summary>
        internal static string FormMerge {
            get {
                return ResourceManager.GetString("FormMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Form Split 的本地化字符串。
        /// </summary>
        internal static string FormSplit {
            get {
                return ResourceManager.GetString("FormSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inconsistent file format! 的本地化字符串。
        /// </summary>
        internal static string InconsistentFileFormat {
            get {
                return ResourceManager.GetString("InconsistentFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input field 的本地化字符串。
        /// </summary>
        internal static string InputField {
            get {
                return ResourceManager.GetString("InputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic detection 的本地化字符串。
        /// </summary>
        internal static string lang_1 {
            get {
                return ResourceManager.GetString("lang_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thai 的本地化字符串。
        /// </summary>
        internal static string lang_10 {
            get {
                return ResourceManager.GetString("lang_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Russian 的本地化字符串。
        /// </summary>
        internal static string lang_11 {
            get {
                return ResourceManager.GetString("lang_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 German 的本地化字符串。
        /// </summary>
        internal static string lang_12 {
            get {
                return ResourceManager.GetString("lang_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traditional Chinese 的本地化字符串。
        /// </summary>
        internal static string lang_13 {
            get {
                return ResourceManager.GetString("lang_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vietnamese 的本地化字符串。
        /// </summary>
        internal static string lang_14 {
            get {
                return ResourceManager.GetString("lang_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese 的本地化字符串。
        /// </summary>
        internal static string lang_2 {
            get {
                return ResourceManager.GetString("lang_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string lang_3 {
            get {
                return ResourceManager.GetString("lang_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cantonese 的本地化字符串。
        /// </summary>
        internal static string lang_4 {
            get {
                return ResourceManager.GetString("lang_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Classical Chinese 的本地化字符串。
        /// </summary>
        internal static string lang_5 {
            get {
                return ResourceManager.GetString("lang_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japanese 的本地化字符串。
        /// </summary>
        internal static string lang_6 {
            get {
                return ResourceManager.GetString("lang_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Korean 的本地化字符串。
        /// </summary>
        internal static string lang_7 {
            get {
                return ResourceManager.GetString("lang_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 French 的本地化字符串。
        /// </summary>
        internal static string lang_8 {
            get {
                return ResourceManager.GetString("lang_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spanish 的本地化字符串。
        /// </summary>
        internal static string lang_9 {
            get {
                return ResourceManager.GetString("lang_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Already the last item, can&apos;t move! 的本地化字符串。
        /// </summary>
        internal static string LastItemCannotMove {
            get {
                return ResourceManager.GetString("LastItemCannotMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layout method 的本地化字符串。
        /// </summary>
        internal static string LayoutMethod {
            get {
                return ResourceManager.GetString("LayoutMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge 的本地化字符串。
        /// </summary>
        internal static string Merge {
            get {
                return ResourceManager.GetString("Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The combined file size is up to 20GB (ie 21474836480Byte or 20971520Kb or 20480MB) 的本地化字符串。
        /// </summary>
        internal static string MergeFileSizeLimit {
            get {
                return ResourceManager.GetString("MergeFileSizeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move down 的本地化字符串。
        /// </summary>
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move up 的本地化字符串。
        /// </summary>
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple workbook merges 的本地化字符串。
        /// </summary>
        internal static string MultipleWorkbookMerges {
            get {
                return ResourceManager.GetString("MultipleWorkbookMerges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple worksheets merged 的本地化字符串。
        /// </summary>
        internal static string MultipleWorksheetsMerges {
            get {
                return ResourceManager.GetString("MultipleWorksheetsMerges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notepad Manage 的本地化字符串。
        /// </summary>
        internal static string NoteBookManage {
            get {
                return ResourceManager.GetString("NoteBookManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NoteBook Merge 的本地化字符串。
        /// </summary>
        internal static string NoteMerge {
            get {
                return ResourceManager.GetString("NoteMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NoteBook Split 的本地化字符串。
        /// </summary>
        internal static string NoteSplit {
            get {
                return ResourceManager.GetString("NoteSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operating 的本地化字符串。
        /// </summary>
        internal static string Operating {
            get {
                return ResourceManager.GetString("Operating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Split based on page breaks 的本地化字符串。
        /// </summary>
        internal static string PageBreakSplit {
            get {
                return ResourceManager.GetString("PageBreakSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set up notebooks, documents, forms and other documents for management, file splitting and merging. Operating environment: Windows platform 的本地化字符串。
        /// </summary>
        internal static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rows 的本地化字符串。
        /// </summary>
        internal static string Rows {
            get {
                return ResourceManager.GetString("Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of rows cannot be empty 的本地化字符串。
        /// </summary>
        internal static string RowsCannotBeEmpty {
            get {
                return ResourceManager.GetString("RowsCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format error, format requirement: positive integer (starting line number), positive integer and 0 (end line number, 0 means last line) 的本地化字符串。
        /// </summary>
        internal static string RowsWrongFormat {
            get {
                return ResourceManager.GetString("RowsWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Split based on section breaks 的本地化字符串。
        /// </summary>
        internal static string SectionBreakSplit {
            get {
                return ResourceManager.GetString("SectionBreakSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the file that needs to be formatted! 的本地化字符串。
        /// </summary>
        internal static string SelectConvertFile {
            get {
                return ResourceManager.GetString("SelectConvertFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a file! 的本地化字符串。
        /// </summary>
        internal static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a file save path! 的本地化字符串。
        /// </summary>
        internal static string SelectFileSavePath {
            get {
                return ResourceManager.GetString("SelectFileSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select items to move! 的本地化字符串。
        /// </summary>
        internal static string SelectItemToMove {
            get {
                return ResourceManager.GetString("SelectItemToMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select items to remove! 的本地化字符串。
        /// </summary>
        internal static string SelectItemToRemove {
            get {
                return ResourceManager.GetString("SelectItemToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number 的本地化字符串。
        /// </summary>
        internal static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simple Calculator 的本地化字符串。
        /// </summary>
        internal static string SimpleCalculator {
            get {
                return ResourceManager.GetString("SimpleCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified worksheet cannot be empty! 的本地化字符串。
        /// </summary>
        internal static string SpecifiedWorksheetCannotBeEmpty {
            get {
                return ResourceManager.GetString("SpecifiedWorksheetCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Segmentation 的本地化字符串。
        /// </summary>
        internal static string Split {
            get {
                return ResourceManager.GetString("Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Split all worksheets into workbooks 的本地化字符串。
        /// </summary>
        internal static string SplitAllWorksheetsIntoWorkbooks {
            get {
                return ResourceManager.GetString("SplitAllWorksheetsIntoWorkbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add custom content to the first line(only 50 characters, content cannot be empty) 的本地化字符串。
        /// </summary>
        internal static string SplitCustomOptions {
            get {
                return ResourceManager.GetString("SplitCustomOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Split file 的本地化字符串。
        /// </summary>
        internal static string SplitFile {
            get {
                return ResourceManager.GetString("SplitFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Split method 的本地化字符串。
        /// </summary>
        internal static string SplitMethod {
            get {
                return ResourceManager.GetString("SplitMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Writing data to file {0} failed! 的本地化字符串。
        /// </summary>
        internal static string SplitPrompt {
            get {
                return ResourceManager.GetString("SplitPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Split type 的本地化字符串。
        /// </summary>
        internal static string SplitType {
            get {
                return ResourceManager.GetString("SplitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Split the worksheet into fixed rows 的本地化字符串。
        /// </summary>
        internal static string SplitWorksheetIntoFixedRows {
            get {
                return ResourceManager.GetString("SplitWorksheetIntoFixedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Manage 的本地化字符串。
        /// </summary>
        internal static string SystemManage {
            get {
                return ResourceManager.GetString("SystemManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge from the end of the paragraph 的本地化字符串。
        /// </summary>
        internal static string TakeEndParagraph {
            get {
                return ResourceManager.GetString("TakeEndParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tool Manage 的本地化字符串。
        /// </summary>
        internal static string ToolManage {
            get {
                return ResourceManager.GetString("ToolManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Management Tool 1.0.0 的本地化字符串。
        /// </summary>
        internal static string ToolVersion {
            get {
                return ResourceManager.GetString("ToolVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation 的本地化字符串。
        /// </summary>
        internal static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: Please use this translation tool if the network is unblocked. 的本地化字符串。
        /// </summary>
        internal static string TranslationNote {
            get {
                return ResourceManager.GetString("TranslationNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation Tool 的本地化字符串。
        /// </summary>
        internal static string TranslationTool {
            get {
                return ResourceManager.GetString("TranslationTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jay Chan reserves all rights 的本地化字符串。
        /// </summary>
        internal static string VersionAll {
            get {
                return ResourceManager.GetString("VersionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Watermark color 的本地化字符串。
        /// </summary>
        internal static string WatermarkColor {
            get {
                return ResourceManager.GetString("WatermarkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagonal 的本地化字符串。
        /// </summary>
        internal static string WatermarkLayoutDiagonal {
            get {
                return ResourceManager.GetString("WatermarkLayoutDiagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Horizontal 的本地化字符串。
        /// </summary>
        internal static string WatermarkLayoutHorizontal {
            get {
                return ResourceManager.GetString("WatermarkLayoutHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Worksheet 的本地化字符串。
        /// </summary>
        internal static string WorkSheet {
            get {
                return ResourceManager.GetString("WorkSheet", resourceCulture);
            }
        }
    }
}
