//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SplitMergeTool.lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_cn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_cn() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SplitMergeTool.lang.zh-cn", typeof(zh_cn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先添加需要合并的文件！ 的本地化字符串。
        /// </summary>
        internal static string AddFileToMerge {
            get {
                return ResourceManager.GetString("AddFileToMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新页合并 的本地化字符串。
        /// </summary>
        internal static string AddNewPageMerge {
            get {
                return ResourceManager.GetString("AddNewPageMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加文本水印 的本地化字符串。
        /// </summary>
        internal static string AddTextWatermark {
            get {
                return ResourceManager.GetString("AddTextWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有工作表 的本地化字符串。
        /// </summary>
        internal static string AllWorksheets {
            get {
                return ResourceManager.GetString("AllWorksheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本信息 的本地化字符串。
        /// </summary>
        internal static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文 的本地化字符串。
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择颜色 的本地化字符串。
        /// </summary>
        internal static string ChooseColor {
            get {
                return ResourceManager.GetString("ChooseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择字体大小 的本地化字符串。
        /// </summary>
        internal static string ChooseFontSize {
            get {
                return ResourceManager.GetString("ChooseFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择工作表 的本地化字符串。
        /// </summary>
        internal static string ChooseWorksheet {
            get {
                return ResourceManager.GetString("ChooseWorksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此操作会移除输出文件路径中原有同名文件，确认执行？ 的本地化字符串。
        /// </summary>
        internal static string ConfirmExecution {
            get {
                return ResourceManager.GetString("ConfirmExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系 的本地化字符串。
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注：联系时请注明是&quot;SplitMergeTool&quot;用户 的本地化字符串。
        /// </summary>
        internal static string ContactNote {
            get {
                return ResourceManager.GetString("ContactNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换类型与文件格式不匹配！ 的本地化字符串。
        /// </summary>
        internal static string ConversionFormatNotMatch {
            get {
                return ResourceManager.GetString("ConversionFormatNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换 的本地化字符串。
        /// </summary>
        internal static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换类型 的本地化字符串。
        /// </summary>
        internal static string ConvertType {
            get {
                return ResourceManager.GetString("ConvertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件地址已复制到剪切板！ 的本地化字符串。
        /// </summary>
        internal static string CopyEmailAddress {
            get {
                return ResourceManager.GetString("CopyEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号码已复制到剪切板！ 的本地化字符串。
        /// </summary>
        internal static string CopyPhoneNumber {
            get {
                return ResourceManager.GetString("CopyPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ号码已复制到剪切板！ 的本地化字符串。
        /// </summary>
        internal static string CopyQQNumber {
            get {
                return ResourceManager.GetString("CopyQQNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CopyRight© 2019 Jay Chan. All Rights Reserved. 的本地化字符串。
        /// </summary>
        internal static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制到剪切板 的本地化字符串。
        /// </summary>
        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微信号已复制到剪切板！ 的本地化字符串。
        /// </summary>
        internal static string CopyWeChatNumber {
            get {
                return ResourceManager.GetString("CopyWeChatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前时间 的本地化字符串。
        /// </summary>
        internal static string CurrDate {
            get {
                return ResourceManager.GetString("CurrDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定工作表 的本地化字符串。
        /// </summary>
        internal static string DesignatedWorksheet {
            get {
                return ResourceManager.GetString("DesignatedWorksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档管理 的本地化字符串。
        /// </summary>
        internal static string DocManage {
            get {
                return ResourceManager.GetString("DocManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档合并 的本地化字符串。
        /// </summary>
        internal static string DocMerge {
            get {
                return ResourceManager.GetString("DocMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档分割 的本地化字符串。
        /// </summary>
        internal static string DocSplit {
            get {
                return ResourceManager.GetString("DocSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string DropOut {
            get {
                return ResourceManager.GetString("DropOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文 的本地化字符串。
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入自定义信息！ 的本地化字符串。
        /// </summary>
        internal static string EnterCustomContent {
            get {
                return ResourceManager.GetString("EnterCustomContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入文件数量！ 的本地化字符串。
        /// </summary>
        internal static string EnterFileCount {
            get {
                return ResourceManager.GetString("EnterFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入文件名！ 的本地化字符串。
        /// </summary>
        internal static string EnterFileName {
            get {
                return ResourceManager.GetString("EnterFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入文件大小！ 的本地化字符串。
        /// </summary>
        internal static string EnterFileSize {
            get {
                return ResourceManager.GetString("EnterFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行完毕！ 的本地化字符串。
        /// </summary>
        internal static string ExecutionCompleted {
            get {
                return ResourceManager.GetString("ExecutionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扩展区域 的本地化字符串。
        /// </summary>
        internal static string ExtendedArea {
            get {
                return ResourceManager.GetString("ExtendedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件数量 的本地化字符串。
        /// </summary>
        internal static string FileCount {
            get {
                return ResourceManager.GetString("FileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件格式转换工具 的本地化字符串。
        /// </summary>
        internal static string FileFormatConversionTool {
            get {
                return ResourceManager.GetString("FileFormatConversionTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件大小 的本地化字符串。
        /// </summary>
        internal static string FileLength {
            get {
                return ResourceManager.GetString("FileLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件列表 的本地化字符串。
        /// </summary>
        internal static string FileList {
            get {
                return ResourceManager.GetString("FileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件管理工具 的本地化字符串。
        /// </summary>
        internal static string FileManageTool {
            get {
                return ResourceManager.GetString("FileManageTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名 的本地化字符串。
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件路径 的本地化字符串。
        /// </summary>
        internal static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件路径错误！ 的本地化字符串。
        /// </summary>
        internal static string FilePathError {
            get {
                return ResourceManager.GetString("FilePathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换文件（可进行文件拖放） 的本地化字符串。
        /// </summary>
        internal static string FilesConvert {
            get {
                return ResourceManager.GetString("FilesConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件大小（字节） 的本地化字符串。
        /// </summary>
        internal static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并文件（可进行文件拖放） 的本地化字符串。
        /// </summary>
        internal static string FilesMerged {
            get {
                return ResourceManager.GetString("FilesMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件类型 的本地化字符串。
        /// </summary>
        internal static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经是第一项，无法移动！ 的本地化字符串。
        /// </summary>
        internal static string FirstItemCannotMove {
            get {
                return ResourceManager.GetString("FirstItemCannotMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体大小 的本地化字符串。
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF转Word 的本地化字符串。
        /// </summary>
        internal static string FormatType0 {
            get {
                return ResourceManager.GetString("FormatType0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF转XPS 的本地化字符串。
        /// </summary>
        internal static string FormatType1 {
            get {
                return ResourceManager.GetString("FormatType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF转BMP 的本地化字符串。
        /// </summary>
        internal static string FormatType10 {
            get {
                return ResourceManager.GetString("FormatType10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF转GIF 的本地化字符串。
        /// </summary>
        internal static string FormatType11 {
            get {
                return ResourceManager.GetString("FormatType11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF转ICON 的本地化字符串。
        /// </summary>
        internal static string FormatType12 {
            get {
                return ResourceManager.GetString("FormatType12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF转Html 的本地化字符串。
        /// </summary>
        internal static string FormatType2 {
            get {
                return ResourceManager.GetString("FormatType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CSV转PDF 的本地化字符串。
        /// </summary>
        internal static string FormatType3 {
            get {
                return ResourceManager.GetString("FormatType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Word转PDF 的本地化字符串。
        /// </summary>
        internal static string FormatType4 {
            get {
                return ResourceManager.GetString("FormatType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XPS转PDF 的本地化字符串。
        /// </summary>
        internal static string FormatType5 {
            get {
                return ResourceManager.GetString("FormatType5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Html转PDF 的本地化字符串。
        /// </summary>
        internal static string FormatType6 {
            get {
                return ResourceManager.GetString("FormatType6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF转PNG 的本地化字符串。
        /// </summary>
        internal static string FormatType7 {
            get {
                return ResourceManager.GetString("FormatType7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel转PDF 的本地化字符串。
        /// </summary>
        internal static string FormatType8 {
            get {
                return ResourceManager.GetString("FormatType8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF转JPG 的本地化字符串。
        /// </summary>
        internal static string FormatType9 {
            get {
                return ResourceManager.GetString("FormatType9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表格管理 的本地化字符串。
        /// </summary>
        internal static string FormManage {
            get {
                return ResourceManager.GetString("FormManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表格合并 的本地化字符串。
        /// </summary>
        internal static string FormMerge {
            get {
                return ResourceManager.GetString("FormMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表格拆分 的本地化字符串。
        /// </summary>
        internal static string FormSplit {
            get {
                return ResourceManager.GetString("FormSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件格式不一致！ 的本地化字符串。
        /// </summary>
        internal static string InconsistentFileFormat {
            get {
                return ResourceManager.GetString("InconsistentFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入域 的本地化字符串。
        /// </summary>
        internal static string InputField {
            get {
                return ResourceManager.GetString("InputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动检测 的本地化字符串。
        /// </summary>
        internal static string lang_1 {
            get {
                return ResourceManager.GetString("lang_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泰语 的本地化字符串。
        /// </summary>
        internal static string lang_10 {
            get {
                return ResourceManager.GetString("lang_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 俄语 的本地化字符串。
        /// </summary>
        internal static string lang_11 {
            get {
                return ResourceManager.GetString("lang_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 德语 的本地化字符串。
        /// </summary>
        internal static string lang_12 {
            get {
                return ResourceManager.GetString("lang_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 繁体中文 的本地化字符串。
        /// </summary>
        internal static string lang_13 {
            get {
                return ResourceManager.GetString("lang_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 越南语 的本地化字符串。
        /// </summary>
        internal static string lang_14 {
            get {
                return ResourceManager.GetString("lang_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文 的本地化字符串。
        /// </summary>
        internal static string lang_2 {
            get {
                return ResourceManager.GetString("lang_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英语 的本地化字符串。
        /// </summary>
        internal static string lang_3 {
            get {
                return ResourceManager.GetString("lang_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粤语 的本地化字符串。
        /// </summary>
        internal static string lang_4 {
            get {
                return ResourceManager.GetString("lang_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文言文 的本地化字符串。
        /// </summary>
        internal static string lang_5 {
            get {
                return ResourceManager.GetString("lang_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日语 的本地化字符串。
        /// </summary>
        internal static string lang_6 {
            get {
                return ResourceManager.GetString("lang_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 韩语 的本地化字符串。
        /// </summary>
        internal static string lang_7 {
            get {
                return ResourceManager.GetString("lang_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 法语 的本地化字符串。
        /// </summary>
        internal static string lang_8 {
            get {
                return ResourceManager.GetString("lang_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 西班牙语 的本地化字符串。
        /// </summary>
        internal static string lang_9 {
            get {
                return ResourceManager.GetString("lang_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经是最后一项，无法移动！ 的本地化字符串。
        /// </summary>
        internal static string LastItemCannotMove {
            get {
                return ResourceManager.GetString("LastItemCannotMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 布局方式 的本地化字符串。
        /// </summary>
        internal static string LayoutMethod {
            get {
                return ResourceManager.GetString("LayoutMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并 的本地化字符串。
        /// </summary>
        internal static string Merge {
            get {
                return ResourceManager.GetString("Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并文件大小最大为20GB（即21474836480Byte或20971520Kb或20480MB） 的本地化字符串。
        /// </summary>
        internal static string MergeFileSizeLimit {
            get {
                return ResourceManager.GetString("MergeFileSizeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多个工作簿合并 的本地化字符串。
        /// </summary>
        internal static string MultipleWorkbookMerges {
            get {
                return ResourceManager.GetString("MultipleWorkbookMerges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多个工作表合并 的本地化字符串。
        /// </summary>
        internal static string MultipleWorksheetsMerges {
            get {
                return ResourceManager.GetString("MultipleWorksheetsMerges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记事本管理 的本地化字符串。
        /// </summary>
        internal static string NoteBookManage {
            get {
                return ResourceManager.GetString("NoteBookManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记事本合并 的本地化字符串。
        /// </summary>
        internal static string NoteMerge {
            get {
                return ResourceManager.GetString("NoteMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记事本拆分 的本地化字符串。
        /// </summary>
        internal static string NoteSplit {
            get {
                return ResourceManager.GetString("NoteSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string Operating {
            get {
                return ResourceManager.GetString("Operating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据分页符进行拆分 的本地化字符串。
        /// </summary>
        internal static string PageBreakSplit {
            get {
                return ResourceManager.GetString("PageBreakSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 集记事本、文档、表格等文件进行管理，可进行文件拆分、合并。运行环境：Windows平台 的本地化字符串。
        /// </summary>
        internal static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除 的本地化字符串。
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行数 的本地化字符串。
        /// </summary>
        internal static string Rows {
            get {
                return ResourceManager.GetString("Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行数不能为空 的本地化字符串。
        /// </summary>
        internal static string RowsCannotBeEmpty {
            get {
                return ResourceManager.GetString("RowsCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式错误，格式要求：正整数（开始行数），正整数与0（结束行数，为0表示最后一行） 的本地化字符串。
        /// </summary>
        internal static string RowsWrongFormat {
            get {
                return ResourceManager.GetString("RowsWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据分节符进行拆分 的本地化字符串。
        /// </summary>
        internal static string SectionBreakSplit {
            get {
                return ResourceManager.GetString("SectionBreakSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择需要进行格式转换的文件！ 的本地化字符串。
        /// </summary>
        internal static string SelectConvertFile {
            get {
                return ResourceManager.GetString("SelectConvertFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择文件！ 的本地化字符串。
        /// </summary>
        internal static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择文件保存路径！ 的本地化字符串。
        /// </summary>
        internal static string SelectFileSavePath {
            get {
                return ResourceManager.GetString("SelectFileSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要移动的项！ 的本地化字符串。
        /// </summary>
        internal static string SelectItemToMove {
            get {
                return ResourceManager.GetString("SelectItemToMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要移除的项！ 的本地化字符串。
        /// </summary>
        internal static string SelectItemToRemove {
            get {
                return ResourceManager.GetString("SelectItemToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        internal static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简易计算器 的本地化字符串。
        /// </summary>
        internal static string SimpleCalculator {
            get {
                return ResourceManager.GetString("SimpleCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的工作表不能为空！ 的本地化字符串。
        /// </summary>
        internal static string SpecifiedWorksheetCannotBeEmpty {
            get {
                return ResourceManager.GetString("SpecifiedWorksheetCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拆分 的本地化字符串。
        /// </summary>
        internal static string Split {
            get {
                return ResourceManager.GetString("Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将所有工作表拆分为工作簿 的本地化字符串。
        /// </summary>
        internal static string SplitAllWorksheetsIntoWorkbooks {
            get {
                return ResourceManager.GetString("SplitAllWorksheetsIntoWorkbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拆分文件内容首行添加自定义内容（仅限50个字符，若勾选此项，则所填内容不能为空） 的本地化字符串。
        /// </summary>
        internal static string SplitCustomOptions {
            get {
                return ResourceManager.GetString("SplitCustomOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拆分文件 的本地化字符串。
        /// </summary>
        internal static string SplitFile {
            get {
                return ResourceManager.GetString("SplitFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拆分方式 的本地化字符串。
        /// </summary>
        internal static string SplitMethod {
            get {
                return ResourceManager.GetString("SplitMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 往文件{0}中写入数据失败！ 的本地化字符串。
        /// </summary>
        internal static string SplitPrompt {
            get {
                return ResourceManager.GetString("SplitPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拆分类型 的本地化字符串。
        /// </summary>
        internal static string SplitType {
            get {
                return ResourceManager.GetString("SplitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将工作表进行固定行数拆分 的本地化字符串。
        /// </summary>
        internal static string SplitWorksheetIntoFixedRows {
            get {
                return ResourceManager.GetString("SplitWorksheetIntoFixedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统管理 的本地化字符串。
        /// </summary>
        internal static string SystemManage {
            get {
                return ResourceManager.GetString("SystemManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 承接段尾合并 的本地化字符串。
        /// </summary>
        internal static string TakeEndParagraph {
            get {
                return ResourceManager.GetString("TakeEndParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具管理 的本地化字符串。
        /// </summary>
        internal static string ToolManage {
            get {
                return ResourceManager.GetString("ToolManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件管理工具1.0.0 的本地化字符串。
        /// </summary>
        internal static string ToolVersion {
            get {
                return ResourceManager.GetString("ToolVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 翻译 的本地化字符串。
        /// </summary>
        internal static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注：请在网络畅通的情况下使用此翻译工具 的本地化字符串。
        /// </summary>
        internal static string TranslationNote {
            get {
                return ResourceManager.GetString("TranslationNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 翻译工具 的本地化字符串。
        /// </summary>
        internal static string TranslationTool {
            get {
                return ResourceManager.GetString("TranslationTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jay Chan 版权所有 的本地化字符串。
        /// </summary>
        internal static string VersionAll {
            get {
                return ResourceManager.GetString("VersionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水印颜色 的本地化字符串。
        /// </summary>
        internal static string WatermarkColor {
            get {
                return ResourceManager.GetString("WatermarkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对角线水印布局 的本地化字符串。
        /// </summary>
        internal static string WatermarkLayoutDiagonal {
            get {
                return ResourceManager.GetString("WatermarkLayoutDiagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水平水印布局 的本地化字符串。
        /// </summary>
        internal static string WatermarkLayoutHorizontal {
            get {
                return ResourceManager.GetString("WatermarkLayoutHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作表 的本地化字符串。
        /// </summary>
        internal static string WorkSheet {
            get {
                return ResourceManager.GetString("WorkSheet", resourceCulture);
            }
        }
    }
}
